# This is a basic workflow to help you get started with Actions

name: Upload

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      artifact-name: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact-name }}
          path: ./upload
          retention-days: 30

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.0
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: OSIMDEV/onecloud-devops-terraform
          event-type: deploy-oneapp-assets-staging
          client-payload: '{"gh_run_id": "${{ github.run_id }}", "gh_run_number": "${{ github.run_number }}", "gh_repo_name": "${{ github.repository  }}", "artifact_name": " ${{ env.artifact-name }}"}'
        
        
        
        
        
        
        
        
        
        
